<?php require_once './templates/header.phtml'; ?>


<form action="login" method='POST'>

    <label for="nombre"></label>
    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingrese su nombre de usuario" required>

    <label for="contrasenia"></label>
    <input type="password" class="form-control" id="contraseniaç" name="contrasenia" placeholder="Ingrese su contraseña" required>

    <button type='submit' class='btn btn-primary'>Ingresar</button>
</form>

<?php require_once './templates/footer.phtml'; ?>
