<?php require './header.php';  ?> 

<form action="login" method='post'>


    <label for="nombre"></label>
    <input type="text" class='form-control' id='nombre' name='nombre' required>
    


    <label for="contrasenia"></label>
    <input type="password" class='form-control' id='contrasenia' name='contrasenia' required>

    <button type='submit' class='btn btn-primary'>Ingresar</button>
</form>

<?php require './footer.php';  ?>  
